### PR TITLE
Added check for programs.

### PR DESCRIPTION
**Pull request by MatanzaBR**

### CODE REVIEW

**Comment by eltonfabricio10** [comment]
@tuxslack,  we thank you for your commitment to contributing to improvements to sparky-tube.

**However, some points need to be observed:**

- The program check should suggest to the user the installation of missing programs instead of simply closing the program.

- The Readme must be in English.

- We believe that "parole" was properly tested before being included in the program.

Submit corrections and we'll take another look at your PR.

Thanks!

**Comment by TeHMoroS** [comment]
I don't hang around Sparky Tube much, but this PR still needs some clean up.

@tuxslack While I appreciate contributions as much as anyone here, we need to follow some guidelines for the code to be understandable to everyone (and I haven't been paying much attention to the repositories lately - my bad).

For starters: why are code comments and text messages in spanish only? Given Sparky is a multi-language community, we should fallback to english for comments and code constructs (variables, function names, etc.).

Messages are another thing: the program is localized with multiple language files in the `lang` directory. That's where all messages should be placed, in unique environment variables, in english first and foremost, with additional translations on a "I can do that" basis (not everyone knows each language - that's understandable, but english is the bare minimum).

Third part: commit descriptions. Right now what we have here are 6 commits with the "Update sparky-tube" description. This says nothing - not one thing about what was done in the commit. There are some nice guideline out there we should probably adopt here, like e.g. this one: https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

The technical part seems to be ok, as far as functionality goes, so the enhancements are ok, but the form in which they are delivered needs some more work. :)

**Comment by tuxslack** [comment]
Can the script work with .mo files for internalization?

Location: /usr/local/share/locale/

**Comment by TeHMoroS** [comment]
@tuxslack Yes, you can use `gettext` to obtain the strings you need:

```bash
$ gettext NetworkManager "Error: No property specified."
Error: No property specified.
```

This will the get string with id "Error: No property specified." (yes, they use english phrases as IDs, so it might be confusing, but it's not like that everywhere) from the NetworkManager domain (basically the `/usr/share/locale/(current locale)/NetworkManager.mo` file).

You can force it to use a locale other than the current system locale simply by setting the LC_ALL environment variable when calling the util:

```
$ LC_ALL=es_ES.UTF-8 gettext NetworkManager "Error: No property specified."
Error: no se especificó ninguna propiedad
```

**Comment by eltonfabricio10** [comment]
Sorry, changes will not be accepted! 
Please try a new PR without changing the program structure.

**Comment by tuxslack** [comment]
> Sorry, changes will not be accepted! Please try a new PR without changing the program structure.


Hello

Can you test it on the project's distro to identify errors?

I'm working on something that may help other distros outside of Debian.

Do you have images of how the script works on SparkyLinux?

I changed the program structure based on the **install.sh** file in the installation part:

**Root user:**

**cp usr /**

Thanks

**Comment by TeHMoroS** [comment]
> I'm working on something that may help other distros outside of Debian.

With all due respect, it's called `sparky-tube` for a reason. While I'm all on board for as generic of an approach as possible, different distros can adjust this on their own. Our priority is to make it work nicely on our distro and generally different versions of it first and foremost. Different versions might have different dependencies and tools available. Until we figure out a good branching model (not a priority sadly), we should maintain the directory structure.

If you want to make a change like that, it's your obligation to test this against the supported versions of Sparky and make sure it works. If not, then please restore the directory structure as it was.

Further more, this PR is already very messy and, **more importantly, out of it's scope** already - "Add check for programs" - the changes here are a lot more than that. If anything, this is a few changes and code refactoring packed up in a single PR. We shouldn't do things like that. If a need to revert the PR arises, we'll have to undo all the changes made. Splitting this up into multiple PRs will allow for a more flexible approach.

The perfect PR structure is:
- one PR per functional change
- refactoring should be a seperate PR
- the perfect amount of commits is 2 tops before review: the changes and any fixes you identify yourself, if you do "self code review"
- additional commits should be one per review roundtrip (everyone approves the code or expresses doubts, then you patch things up and push a commit - then another round begins)

Of course we don't have these practices formally yet, but by following them, we'll be able to keep a clean, maintainable codebase. At the very least concentrate on "one PR per feature" and "seperate refactoring PRs".

**Comment by tuxslack** [comment]
New update

**Bug:**

   \nYou have not entered any URL! \n\nExiting...    => line 1086 - /usr/local/bin/sparky-tube.sh (Gettext is not recognizing the use of \n (line break) within the translation string.)

   Help Function => ajuda()    => line 759 - /usr/local/bin/sparky-tube.sh (Translate long text with gettext only in parts)


   The PLAYER is not opening a file with a name that has accents, white space and special characters => line 1457 - /usr/local/bin/sparky-tube.sh

   "$PLAYLST" "${FILE%.*}.$PLAYFORMAT" 2>/dev/null &

**Pull request closed without merging**
